mcc: '001'
mnc: '01'

nci: '0x000000010'
idLength: 32
tac: 1

linkIp: "172.20.0.20" # rannet의 서브넷 대역에 맞게 설정
ngapIp: "172.18.0.20" # 5gnet의 서브넷 대역에 맞게 설정
# gtpIp: "0.0.0.0"
gtpIp: "172.18.0.20"
# 172.17.0.1 넣어도 된다고 함.
amfConfigs:
  - address: o5gs-amf
    port: 38412

slices:
  - sst: 1
    sd: 1
ignoreStreamIds: true
