# SUPI / IMSI
supi: "imsi-001010000000001"
mcc: "001"
mnc: "01"

# Disable SUCI encryption for simplicity
protectionScheme: 0
routingIndicator: "0000"

# Authentication keys
key: "00112233445566778899AABBCCDDEEFF"
op: "E8ED289DEBA952E4283B54E88E6183CA"
opType: "OP"
amf: "8000"

# Device identity
imei: "356938035643803"
imeiSv: "4370816125816151"

# UE IP interface
tunNetmask: "255.255.255.0"

# gNB search list
gnbSearchList:
  - "RAN-GNB"

# Access identities
uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# PDU session setup (not used until Core is available)
sessions:
  - type: "IPv4"
    apn: "internet"
    slice:
      sst: 1
      sd: 1

# NSSAI configuration
configured-nssai:
  - sst: 1
    sd: 1

default-nssai:
  - sst: 1
    sd: 1

# UE supported integrity algorithms
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity rate
integrityMaxRate:
  uplink: "full"
  downlink: "full"
