logger:
  level: info

smf:
  sbi: # 다른 NF들과 통신하는 포트(HTTP를 사용)
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: o5gs-smf
    client:
      scp:
        - uri: http://o5gs-scp:7777
  
  pfcp: # UPF와 통신하는 포트(PFCP 프로토콜 사용) UPF 제어
    server:
      - address: 0.0.0.0
        advertise: o5gs-smf
        
    client:
      upf:
        - address: o5gs-upf
  
  gtpc:
    server:
      - address: 0.0.0.0
  
  gtpu:
    server:
      - address: 0.0.0.0
  


  session: # UE에게 할당할 IP 주소 대역
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet # Default DNN
    - subnet: 2001:db8:cafe::/48
      gateway: 2001:db8:cafe::1  
      dnn: internet # Default DNN  
  
  dns: # UE가 사용할 DNS 서버 주소
    - 8.8.8.8
    - 8.8.4.4
  
  info:
    - s_nssai:
        - sst: 1
          sd: 1
          dnn:
            - internet
