logger:
  level: info

udr:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: o5gs-udr
    client:
      scp:
        - uri: http://o5gs-scp:7777

db_uri: mongodb://o5gs-mongo/open5gs
